# Generated by Django 4.0.4 on 2022-04-22 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 22, 13, 32, 7, 842170, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 22, 13, 32, 15, 56878, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionyearmodel',
            name='session_end_year',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 32, 19, 764224, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionyearmodel',
            name='session_start_year',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 13, 32, 24, 708297, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sessionyearmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
